<?php
/**
 * CashInpostPayload
 *
 * PHP version 5
 *
 * @category Class
 * @package  rcvs_100
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Receive Side Callback API
 *
 * To facilitate the implementation of mVisa, Visa provides mVisa Receive Side API specifications to clients who implement a set of outbound RESTful APIs (Receive Side APIs) so that Visa can call these APIs to request clients to process the transactions over the Internet.
 *
 * OpenAPI spec version: v1
 * Contact: 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace rcvs_100\model;

use \ArrayAccess;

/**
 * CashInpostPayload Class Doc Comment
 *
 * @category    Class
 * @description Request body for Receive Cash-In API
 * @package     rcvs_100
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CashInpostPayload implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'cashInpostPayload';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'local_transaction_time' => 'string',
        'visa_transaction_id' => 'string',
        'originator_country_code' => 'string',
        'decimal_position_indicator' => 'string',
        'transaction_currency_code' => 'string',
        'velocity_limit_indicator' => 'string',
        'retrieval_reference_number' => 'string',
        'system_trace_audit_number' => 'string',
        'local_transaction_date' => 'string',
        'enc_agent_name' => 'string',
        'originator_bin' => 'string',
        'agent_city' => 'string',
        'enc_consumer_pan' => 'string',
        'transaction_amount' => 'string',
        'transmission_date_time' => 'string'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'local_transaction_time' => 'localTransactionTime',
        'visa_transaction_id' => 'visaTransactionId',
        'originator_country_code' => 'originatorCountryCode',
        'decimal_position_indicator' => 'decimalPositionIndicator',
        'transaction_currency_code' => 'transactionCurrencyCode',
        'velocity_limit_indicator' => 'velocityLimitIndicator',
        'retrieval_reference_number' => 'retrievalReferenceNumber',
        'system_trace_audit_number' => 'systemTraceAuditNumber',
        'local_transaction_date' => 'localTransactionDate',
        'enc_agent_name' => 'encAgentName',
        'originator_bin' => 'originatorBIN',
        'agent_city' => 'agentCity',
        'enc_consumer_pan' => 'encConsumerPAN',
        'transaction_amount' => 'transactionAmount',
        'transmission_date_time' => 'transmissionDateTime'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'local_transaction_time' => 'setLocalTransactionTime',
        'visa_transaction_id' => 'setVisaTransactionId',
        'originator_country_code' => 'setOriginatorCountryCode',
        'decimal_position_indicator' => 'setDecimalPositionIndicator',
        'transaction_currency_code' => 'setTransactionCurrencyCode',
        'velocity_limit_indicator' => 'setVelocityLimitIndicator',
        'retrieval_reference_number' => 'setRetrievalReferenceNumber',
        'system_trace_audit_number' => 'setSystemTraceAuditNumber',
        'local_transaction_date' => 'setLocalTransactionDate',
        'enc_agent_name' => 'setEncAgentName',
        'originator_bin' => 'setOriginatorBin',
        'agent_city' => 'setAgentCity',
        'enc_consumer_pan' => 'setEncConsumerPan',
        'transaction_amount' => 'setTransactionAmount',
        'transmission_date_time' => 'setTransmissionDateTime'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'local_transaction_time' => 'getLocalTransactionTime',
        'visa_transaction_id' => 'getVisaTransactionId',
        'originator_country_code' => 'getOriginatorCountryCode',
        'decimal_position_indicator' => 'getDecimalPositionIndicator',
        'transaction_currency_code' => 'getTransactionCurrencyCode',
        'velocity_limit_indicator' => 'getVelocityLimitIndicator',
        'retrieval_reference_number' => 'getRetrievalReferenceNumber',
        'system_trace_audit_number' => 'getSystemTraceAuditNumber',
        'local_transaction_date' => 'getLocalTransactionDate',
        'enc_agent_name' => 'getEncAgentName',
        'originator_bin' => 'getOriginatorBin',
        'agent_city' => 'getAgentCity',
        'enc_consumer_pan' => 'getEncConsumerPan',
        'transaction_amount' => 'getTransactionAmount',
        'transmission_date_time' => 'getTransmissionDateTime'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['local_transaction_time'] = isset($data['local_transaction_time']) ? $data['local_transaction_time'] : null;
        $this->container['visa_transaction_id'] = isset($data['visa_transaction_id']) ? $data['visa_transaction_id'] : null;
        $this->container['originator_country_code'] = isset($data['originator_country_code']) ? $data['originator_country_code'] : null;
        $this->container['decimal_position_indicator'] = isset($data['decimal_position_indicator']) ? $data['decimal_position_indicator'] : null;
        $this->container['transaction_currency_code'] = isset($data['transaction_currency_code']) ? $data['transaction_currency_code'] : null;
        $this->container['velocity_limit_indicator'] = isset($data['velocity_limit_indicator']) ? $data['velocity_limit_indicator'] : null;
        $this->container['retrieval_reference_number'] = isset($data['retrieval_reference_number']) ? $data['retrieval_reference_number'] : null;
        $this->container['system_trace_audit_number'] = isset($data['system_trace_audit_number']) ? $data['system_trace_audit_number'] : null;
        $this->container['local_transaction_date'] = isset($data['local_transaction_date']) ? $data['local_transaction_date'] : null;
        $this->container['enc_agent_name'] = isset($data['enc_agent_name']) ? $data['enc_agent_name'] : null;
        $this->container['originator_bin'] = isset($data['originator_bin']) ? $data['originator_bin'] : null;
        $this->container['agent_city'] = isset($data['agent_city']) ? $data['agent_city'] : null;
        $this->container['enc_consumer_pan'] = isset($data['enc_consumer_pan']) ? $data['enc_consumer_pan'] : null;
        $this->container['transaction_amount'] = isset($data['transaction_amount']) ? $data['transaction_amount'] : null;
        $this->container['transmission_date_time'] = isset($data['transmission_date_time']) ? $data['transmission_date_time'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if ($this->container['local_transaction_time'] === null) {
            $invalid_properties[] = "'local_transaction_time' can't be null";
        }
        if ($this->container['visa_transaction_id'] === null) {
            $invalid_properties[] = "'visa_transaction_id' can't be null";
        }
        if ($this->container['originator_country_code'] === null) {
            $invalid_properties[] = "'originator_country_code' can't be null";
        }
        if ($this->container['decimal_position_indicator'] === null) {
            $invalid_properties[] = "'decimal_position_indicator' can't be null";
        }
        if ($this->container['transaction_currency_code'] === null) {
            $invalid_properties[] = "'transaction_currency_code' can't be null";
        }
        if ($this->container['retrieval_reference_number'] === null) {
            $invalid_properties[] = "'retrieval_reference_number' can't be null";
        }
        if ($this->container['system_trace_audit_number'] === null) {
            $invalid_properties[] = "'system_trace_audit_number' can't be null";
        }
        if ($this->container['local_transaction_date'] === null) {
            $invalid_properties[] = "'local_transaction_date' can't be null";
        }
        if ($this->container['enc_agent_name'] === null) {
            $invalid_properties[] = "'enc_agent_name' can't be null";
        }
        if ($this->container['originator_bin'] === null) {
            $invalid_properties[] = "'originator_bin' can't be null";
        }
        if ($this->container['agent_city'] === null) {
            $invalid_properties[] = "'agent_city' can't be null";
        }
        if ($this->container['enc_consumer_pan'] === null) {
            $invalid_properties[] = "'enc_consumer_pan' can't be null";
        }
        if ($this->container['transaction_amount'] === null) {
            $invalid_properties[] = "'transaction_amount' can't be null";
        }
        if ($this->container['transmission_date_time'] === null) {
            $invalid_properties[] = "'transmission_date_time' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['local_transaction_time'] === null) {
            return false;
        }
        if ($this->container['visa_transaction_id'] === null) {
            return false;
        }
        if ($this->container['originator_country_code'] === null) {
            return false;
        }
        if ($this->container['decimal_position_indicator'] === null) {
            return false;
        }
        if ($this->container['transaction_currency_code'] === null) {
            return false;
        }
        if ($this->container['retrieval_reference_number'] === null) {
            return false;
        }
        if ($this->container['system_trace_audit_number'] === null) {
            return false;
        }
        if ($this->container['local_transaction_date'] === null) {
            return false;
        }
        if ($this->container['enc_agent_name'] === null) {
            return false;
        }
        if ($this->container['originator_bin'] === null) {
            return false;
        }
        if ($this->container['agent_city'] === null) {
            return false;
        }
        if ($this->container['enc_consumer_pan'] === null) {
            return false;
        }
        if ($this->container['transaction_amount'] === null) {
            return false;
        }
        if ($this->container['transmission_date_time'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets local_transaction_time
     * @return string
     */
    public function getLocalTransactionTime()
    {
        return $this->container['local_transaction_time'];
    }

    /**
     * Sets local_transaction_time
     * @param string $local_transaction_time The time the transaction takes place, expressed in the local time of the originator. The time is in hhmmss format.
     * @return $this
     */
    public function setLocalTransactionTime($local_transaction_time)
    {
        $this->container['local_transaction_time'] = $local_transaction_time;

        return $this;
    }

    /**
     * Gets visa_transaction_id
     * @return string
     */
    public function getVisaTransactionId()
    {
        return $this->container['visa_transaction_id'];
    }

    /**
     * Sets visa_transaction_id
     * @param string $visa_transaction_id Numeric. It contains a right-justified, VisaNet generated Transaction Identifier (TID) that is unique for each request. The identifier links original messages to subsequent messages, such as those for exception item processing and clearing record.
     * @return $this
     */
    public function setVisaTransactionId($visa_transaction_id)
    {
        $this->container['visa_transaction_id'] = $visa_transaction_id;

        return $this;
    }

    /**
     * Gets originator_country_code
     * @return string
     */
    public function getOriginatorCountryCode()
    {
        return $this->container['originator_country_code'];
    }

    /**
     * Sets originator_country_code
     * @param string $originator_country_code A 3-digit ISO-4217 code that identifies the country of the originating BIN.<br>Refer to <a href=\"/request_response_codes#iso_country_codes\">ISO codes</a>.
     * @return $this
     */
    public function setOriginatorCountryCode($originator_country_code)
    {
        $this->container['originator_country_code'] = $originator_country_code;

        return $this;
    }

    /**
     * Gets decimal_position_indicator
     * @return string
     */
    public function getDecimalPositionIndicator()
    {
        return $this->container['decimal_position_indicator'];
    }

    /**
     * Sets decimal_position_indicator
     * @param string $decimal_position_indicator Indicates the number of decimal positions following the amount field. This field is to be sent as NULL if it is not populated.
     * @return $this
     */
    public function setDecimalPositionIndicator($decimal_position_indicator)
    {
        $this->container['decimal_position_indicator'] = $decimal_position_indicator;

        return $this;
    }

    /**
     * Gets transaction_currency_code
     * @return string
     */
    public function getTransactionCurrencyCode()
    {
        return $this->container['transaction_currency_code'];
    }

    /**
     * Sets transaction_currency_code
     * @param string $transaction_currency_code The 3-digit ISO-4217 code in this field reflects the currency associated to the transactionAmount field.
     * @return $this
     */
    public function setTransactionCurrencyCode($transaction_currency_code)
    {
        $this->container['transaction_currency_code'] = $transaction_currency_code;

        return $this;
    }

    /**
     * Gets velocity_limit_indicator
     * @return string
     */
    public function getVelocityLimitIndicator()
    {
        return $this->container['velocity_limit_indicator'];
    }

    /**
     * Sets velocity_limit_indicator
     * @param string $velocity_limit_indicator <b>Conditional</b>. This field contains the velocity limit related information that Acquirer can use in making the authorization decision:<ul><li>1 = 1-day count or amount exceeded.</li><li>2 = 7-day count or amount exceeded.</li><li>3 = 30-day count or amount exceeded.</li></ul>The field is populated with priority of 1, 2 and then 3.<br>This field is sent if recipient has opted for VisaNet to forward them the OCT when a velocity limit has been exceeded.<br>This field will be sent as NULL if it is not populated.
     * @return $this
     */
    public function setVelocityLimitIndicator($velocity_limit_indicator)
    {
        $this->container['velocity_limit_indicator'] = $velocity_limit_indicator;

        return $this;
    }

    /**
     * Gets retrieval_reference_number
     * @return string
     */
    public function getRetrievalReferenceNumber()
    {
        return $this->container['retrieval_reference_number'];
    }

    /**
     * Sets retrieval_reference_number
     * @param string $retrieval_reference_number Numeric. It is a key data element for matching a message to others within a given transaction set. The same number appears in all related messages: response, advice, reversal, chargeback, chargeback reversal, or representment. The format is recommended to be <b>ydddhhnnnnnn</b>.
     * @return $this
     */
    public function setRetrievalReferenceNumber($retrieval_reference_number)
    {
        $this->container['retrieval_reference_number'] = $retrieval_reference_number;

        return $this;
    }

    /**
     * Gets system_trace_audit_number
     * @return string
     */
    public function getSystemTraceAuditNumber()
    {
        return $this->container['system_trace_audit_number'];
    }

    /**
     * Sets system_trace_audit_number
     * @param string $system_trace_audit_number Numeric. It is a key data element used to match a response to its request or to match a message to others for a given transaction.
     * @return $this
     */
    public function setSystemTraceAuditNumber($system_trace_audit_number)
    {
        $this->container['system_trace_audit_number'] = $system_trace_audit_number;

        return $this;
    }

    /**
     * Gets local_transaction_date
     * @return string
     */
    public function getLocalTransactionDate()
    {
        return $this->container['local_transaction_date'];
    }

    /**
     * Sets local_transaction_date
     * @param string $local_transaction_date It contains the local month and day on which the transaction was originated. The date is in mmdd format.
     * @return $this
     */
    public function setLocalTransactionDate($local_transaction_date)
    {
        $this->container['local_transaction_date'] = $local_transaction_date;

        return $this;
    }

    /**
     * Gets enc_agent_name
     * @return string
     */
    public function getEncAgentName()
    {
        return $this->container['enc_agent_name'];
    }

    /**
     * Sets enc_agent_name
     * @param string $enc_agent_name Contains Agent’s Doing Business as name (25 characters only). If the name is greater than 25 characters then the first 25 characters are populated. The field is sent in encrypted format using the AES GCM (i.e. Advanced Encryption Standard (AES) in Galois/Counter Mode (GCM)) algorithm for JSON Web Encryption (JWE) objects with 256-bit key (i.e. the shared secret between Visa and client for encryption and decryption of payload data).
     * @return $this
     */
    public function setEncAgentName($enc_agent_name)
    {
        $this->container['enc_agent_name'] = $enc_agent_name;

        return $this;
    }

    /**
     * Gets originator_bin
     * @return string
     */
    public function getOriginatorBin()
    {
        return $this->container['originator_bin'];
    }

    /**
     * Sets originator_bin
     * @param string $originator_bin This BIN number identifies the originator of Cash-In payment transaction.
     * @return $this
     */
    public function setOriginatorBin($originator_bin)
    {
        $this->container['originator_bin'] = $originator_bin;

        return $this;
    }

    /**
     * Gets agent_city
     * @return string
     */
    public function getAgentCity()
    {
        return $this->container['agent_city'];
    }

    /**
     * Sets agent_city
     * @param string $agent_city Agent city name.
     * @return $this
     */
    public function setAgentCity($agent_city)
    {
        $this->container['agent_city'] = $agent_city;

        return $this;
    }

    /**
     * Gets enc_consumer_pan
     * @return string
     */
    public function getEncConsumerPan()
    {
        return $this->container['enc_consumer_pan'];
    }

    /**
     * Sets enc_consumer_pan
     * @param string $enc_consumer_pan Consumer PAN. This is a 16-digit PAN. The field is sent in encrypted format using the AES GCM (i.e. Advanced Encryption Standard (AES) in Galois/Counter Mode (GCM)) algorithm for JSON Web Encryption (JWE) objects with 256-bit key (i.e. the shared secret between Visa and client for encryption and decryption of payload data). The field data type will be string(16-19) after decryption.
     * @return $this
     */
    public function setEncConsumerPan($enc_consumer_pan)
    {
        $this->container['enc_consumer_pan'] = $enc_consumer_pan;

        return $this;
    }

    /**
     * Gets transaction_amount
     * @return string
     */
    public function getTransactionAmount()
    {
        return $this->container['transaction_amount'];
    }

    /**
     * Sets transaction_amount
     * @param string $transaction_amount Transaction amount in local currency. mVisa program rules do not permit cross border cash deposit transactions.
     * @return $this
     */
    public function setTransactionAmount($transaction_amount)
    {
        $this->container['transaction_amount'] = $transaction_amount;

        return $this;
    }

    /**
     * Gets transmission_date_time
     * @return string
     */
    public function getTransmissionDateTime()
    {
        return $this->container['transmission_date_time'];
    }

    /**
     * Sets transmission_date_time
     * @param string $transmission_date_time The date and time the request was submitted to Visa. Format: MMDDhhmmss.
     * @return $this
     */
    public function setTransmissionDateTime($transmission_date_time)
    {
        $this->container['transmission_date_time'] = $transmission_date_time;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\rcvs_100\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\rcvs_100\ObjectSerializer::sanitizeForSerialization($this));
    }
}

/**
* ----------------------------------------------------------------------------------------------------------------------
*
* © Copyright 2018 Visa. All Rights Reserved.
*
* NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of
* and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property
* rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.
*
* By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy
* (developer.visa.com/privacy). In addition, all permissible uses of the Software must be in support of Visa products,
* programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com).
* THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL
* FAULTS” BASIS WITHOUT WARRANTY OR CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.
* ----------------------------------------------------------------------------------------------------------------------
*/