<?php
/**
 * CashInpostPayloadTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  rcvs_100
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Receive Side Callback API
 *
 * To facilitate the implementation of mVisa, Visa provides mVisa Receive Side API specifications to clients who implement a set of outbound RESTful APIs (Receive Side APIs) so that Visa can call these APIs to request clients to process the transactions over the Internet.
 *
 * OpenAPI spec version: v1
 * Contact: 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace rcvs_100\modeltest;

/**
 * CashInpostPayloadTest Class Doc Comment
 *
 * @category    Class */
// * @description Request body for Receive Cash-In API
/**
 * @package     rcvs_100
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CashInpostPayloadTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "CashInpostPayload"
     */
    public function testCashInpostPayload()
    {

    }

    /**
     * Test attribute "local_transaction_time"
     */
    public function testPropertyLocalTransactionTime()
    {

    }

    /**
     * Test attribute "visa_transaction_id"
     */
    public function testPropertyVisaTransactionId()
    {

    }

    /**
     * Test attribute "originator_country_code"
     */
    public function testPropertyOriginatorCountryCode()
    {

    }

    /**
     * Test attribute "decimal_position_indicator"
     */
    public function testPropertyDecimalPositionIndicator()
    {

    }

    /**
     * Test attribute "transaction_currency_code"
     */
    public function testPropertyTransactionCurrencyCode()
    {

    }

    /**
     * Test attribute "velocity_limit_indicator"
     */
    public function testPropertyVelocityLimitIndicator()
    {

    }

    /**
     * Test attribute "retrieval_reference_number"
     */
    public function testPropertyRetrievalReferenceNumber()
    {

    }

    /**
     * Test attribute "system_trace_audit_number"
     */
    public function testPropertySystemTraceAuditNumber()
    {

    }

    /**
     * Test attribute "local_transaction_date"
     */
    public function testPropertyLocalTransactionDate()
    {

    }

    /**
     * Test attribute "enc_agent_name"
     */
    public function testPropertyEncAgentName()
    {

    }

    /**
     * Test attribute "originator_bin"
     */
    public function testPropertyOriginatorBin()
    {

    }

    /**
     * Test attribute "agent_city"
     */
    public function testPropertyAgentCity()
    {

    }

    /**
     * Test attribute "enc_consumer_pan"
     */
    public function testPropertyEncConsumerPan()
    {

    }

    /**
     * Test attribute "transaction_amount"
     */
    public function testPropertyTransactionAmount()
    {

    }

    /**
     * Test attribute "transmission_date_time"
     */
    public function testPropertyTransmissionDateTime()
    {

    }

}


/**
* --------------------------------------------------------------------------------
*
* © Copyright 2018 Visa. All Rights Reserved.
*
* NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of
* and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property
* rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.
*
* By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy
* (developer.visa.com/privacy). In addition, all permissible uses of the Software must be in support of Visa products,
* programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com).
* THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL
* FAULTS” BASIS WITHOUT WARRANTY OR CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.
* --------------------------------------------------------------------------------
*/